WIP: Add lxd_project resource type #238
terraform-lxd/terraform-provider-lxd pull request #279
Opened 2022-12-14 18:45 UTC by dorkamotorka

**project** configuration parameter should work with every other resource (there is just a slight "issue" with **lxd_network**. Look here for an update on the issue: #278)  

I also added basic unit-testing and verified the functionality on a local setup. This PR still lacks documentation, but I plan to do this once all the software-related things are successfully done.

2022-12-15 07:23 UTC, jtopjian commented
@dorkamotorka To get around the test suite requiring approval, submit a small PR with an update/change to something simple like documentation. I'll merge it and that should help.

2022-12-15 19:40 UTC, dorkamotorka commented
@jtopjian the test suite seems to run fine and the *_project tests seem to work fine until the actions just fail. Is it possible that this is due to a time limit or something because there seem to be NO tests that actually fail?

2022-12-15 20:40 UTC, jtopjian commented
@dorkamotorka It looks like the following test is failing:

```
=== RUN   TestAccNetwork_project
    testing.go:705: Step 0 error: Check failed: Check 2/2 error: Not found: lxd_network.eth0
--- FAIL: TestAccNetwork_project (4.45s)
```

2022-12-15 21:14 UTC, dorkamotorka commented
@jtopjian Sorry, I missed that - thanks for your patience. The test suite now passes which was expected, but I guess the real question is whether the tests I created are sufficient.

2022-12-16 00:11 UTC, jtopjian commented
@dorkamotorka Nice work :)

I skimmed the tests and they look comparable to what we already have, so that should be good. The tests in this project rely heavily on the resource being updated via the API and then triggering a mismatch if one exists. The key piece of code is this area:

https://github.com/terraform-lxd/terraform-provider-lxd/pull/279/files#diff-dbeb3335f87880a6b9890154c58c29425b3d552c639f7fd3d76ef349cd4acf6dR91-R100

(which it looks like there might be a typo here, setting name to config)

The `d.Set()` stuff sets the resource property to what was retrieved by the API. So if, for some reason, the resource created a project called "Foo" but the API returned "Bar", Terraform would flag it due to this bit of code (including in tests). Without this bit of code, the mismatch would continue unnoticed.

Let me know if that makes sense.

2022-12-16 10:29 UTC, dorkamotorka commented
Nice catch of the typo! If I understood you correctly the issue should be fixed.

2022-12-17 16:14 UTC, jtopjian requested changes
@dorkamotorka Thank you for working on this. In general, this is really good. I just have a few requests about documentation wording and coding consistency. Please let me know if you have any questions.

2022-12-17 16:14 UTC, jtopjian commented on lxd/resource_lxd_cached_image.go
> +	if p, ok := d.GetOk("project"); ok && p != "" {
nit: I recommend using `v, ok` which is more consistent with other coding patterns in this project. This comment applies to all occurrences of where you have:

```
if p, ok := ...
```

2022-12-18 09:55 UTC, dorkamotorka commented
Thanks for the review 💯  I think I managed to apply all your suggestions

2022-12-19 18:26 UTC, jtopjian commented
@dorkamotorka Thanks. This all looks good to me. Were you planning to do any other work or is this ready to be merged?

2022-12-19 21:36 UTC, dorkamotorka commented
We can merge this. Thanks for the review 💯

2022-12-20 04:21 UTC, merged

2022-12-20 21:17 UTC, dontlaugh commented
Thank you @dorkamotorka